/var/slurmd/spool/slurmd/job39172148/slurm_script: line 14: mamba: command not found
/var/slurmd/spool/slurmd/job39172148/slurm_script: line 23: cd: /n/home10/colson/helpers: No such file or directory
/var/slurmd/spool/slurmd/job39172148/slurm_script: line 25: kill: `': not a pid or valid job spec
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0100   450  100   450    0     0   109k      0 --:--:-- --:--:-- --:--:--  109k
/var/slurmd/spool/slurmd/job39172148/slurm_script: line 30: jq: command not found
[I 2024-07-09 14:29:34.406 ServerApp] jupyter_lsp | extension was successfully linked.
[I 2024-07-09 14:29:34.425 ServerApp] jupyter_server_terminals | extension was successfully linked.
[W 2024-07-09 14:29:34.440 LabApp] 'token' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2024-07-09 14:29:34.442 ServerApp] ServerApp.token config is deprecated in 2.0. Use IdentityProvider.token.
[I 2024-07-09 14:29:34.442 ServerApp] jupyterlab | extension was successfully linked.
[I 2024-07-09 14:29:34.459 ServerApp] notebook | extension was successfully linked.
[I 2024-07-09 14:29:40.279 ServerApp] notebook_shim | extension was successfully linked.
[I 2024-07-09 14:29:40.679 ServerApp] notebook_shim | extension was successfully loaded.
[I 2024-07-09 14:29:40.683 ServerApp] jupyter_lsp | extension was successfully loaded.
[I 2024-07-09 14:29:40.683 ServerApp] jupyter_server_terminals | extension was successfully loaded.
[I 2024-07-09 14:29:40.985 LabApp] JupyterLab extension loaded from /n/home10/colson/.conda/envs/gpu/lib/python3.12/site-packages/jupyterlab
[I 2024-07-09 14:29:40.985 LabApp] JupyterLab application directory is /n/home10/colson/.conda/envs/gpu/share/jupyter/lab
[I 2024-07-09 14:29:41.018 LabApp] Extension Manager is 'pypi'.
[I 2024-07-09 14:29:41.021 ServerApp] jupyterlab | extension was successfully loaded.
[I 2024-07-09 14:29:41.092 ServerApp] notebook | extension was successfully loaded.
[I 2024-07-09 14:29:41.092 ServerApp] Serving notebooks from local directory: /n/home10/colson
[I 2024-07-09 14:29:41.092 ServerApp] Jupyter Server 2.14.0 is running at:
[I 2024-07-09 14:29:41.092 ServerApp] http://holy8a26501.rc.fas.harvard.edu:8889/lab?token=...
[I 2024-07-09 14:29:41.092 ServerApp]     http://127.0.0.1:8889/lab?token=...
[I 2024-07-09 14:29:41.092 ServerApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[I 2024-07-09 14:29:41.343 ServerApp] Skipped non-installed server(s): bash-language-server, dockerfile-language-server-nodejs, javascript-typescript-langserver, jedi-language-server, julia-language-server, pyright, python-language-server, python-lsp-server, r-languageserver, sql-language-server, texlab, typescript-language-server, unified-language-server, vscode-css-languageserver-bin, vscode-html-languageserver-bin, vscode-json-languageserver-bin, yaml-language-server
[W 2024-07-09 14:31:37.252 LabApp] Could not determine jupyterlab build status without nodejs
[I 2024-07-09 14:31:37.942 ServerApp] New terminal with automatic name: 3
[W 2024-07-09 14:31:41.200 ServerApp] 404 GET /api/contents/.local/lib/python3.10/site-packages/torch/_functorch/deprecated.py?content=0&hash=0&1720549900990 (0a59656efe9c4c488fcb3e9f5f3e74e9@127.0.0.1) 34.33ms referer=https://f200-140-247-111-5.ngrok-free.app/lab
[I 2024-07-09 14:31:41.200 ServerApp] Refusing to serve hidden file or directory '/n/home10/colson/.local/lib/python3.10/site-packages/torch/_functorch/deprecated.py', via 404 Error
[E 2024-07-09 14:31:41.201 ServerApp] Uncaught exception GET /api/contents/.local/lib/python3.10/site-packages/torch/_functorch/deprecated.py?content=0&hash=0&1720549900990 (127.0.0.1)
    HTTPServerRequest(protocol='http', host='f200-140-247-111-5.ngrok-free.app', method='GET', uri='/api/contents/.local/lib/python3.10/site-packages/torch/_functorch/deprecated.py?content=0&hash=0&1720549900990', version='HTTP/1.1', remote_ip='127.0.0.1')
    Traceback (most recent call last):
      File "/n/home10/colson/.conda/envs/gpu/lib/python3.12/site-packages/jupyter_server/services/contents/handlers.py", line 154, in get
        model = await ensure_async(
                ^^^^^^^^^^^^^^^^^^^
      File "/n/home10/colson/.conda/envs/gpu/lib/python3.12/site-packages/jupyter_core/utils/__init__.py", line 198, in ensure_async
        result = await obj
                 ^^^^^^^^^
      File "/n/home10/colson/.conda/envs/gpu/lib/python3.12/site-packages/jupyter_server/services/contents/filemanager.py", line 923, in get
        model = await self._file_model(
                ^^^^^^^^^^^^^^^^^^^^^^^
      File "/n/home10/colson/.conda/envs/gpu/lib/python3.12/site-packages/jupyter_server/services/contents/filemanager.py", line 824, in _file_model
        model = self._base_model(path)
                ^^^^^^^^^^^^^^^^^^^^^^
      File "/n/home10/colson/.conda/envs/gpu/lib/python3.12/site-packages/jupyter_server/services/contents/filemanager.py", line 236, in _base_model
        raise web.HTTPError(404, four_o_four)
    tornado.web.HTTPError: HTTP 404: Not Found (file or directory does not exist: '.local/lib/python3.10/site-packages/torch/_functorch/deprecated.py')
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/n/home10/colson/.conda/envs/gpu/lib/python3.12/site-packages/tornado/web.py", line 1790, in _execute
        result = await result
                 ^^^^^^^^^^^^
      File "/n/home10/colson/.conda/envs/gpu/lib/python3.12/site-packages/jupyter_server/auth/decorator.py", line 73, in inner
        return await out
               ^^^^^^^^^
      File "/n/home10/colson/.conda/envs/gpu/lib/python3.12/site-packages/jupyter_server/services/contents/handlers.py", line 180, in get
        await self._finish_error(
      File "/n/home10/colson/.conda/envs/gpu/lib/python3.12/site-packages/jupyter_server/services/contents/handlers.py", line 114, in _finish_error
        self.write(message)
      File "/n/home10/colson/.conda/envs/gpu/lib/python3.12/site-packages/tornado/web.py", line 914, in write
        raise RuntimeError("Cannot write() after finish()")
    RuntimeError: Cannot write() after finish()
[I 2024-07-09 14:31:41.608 ServerApp] Kernel started: efd695ea-963d-410b-b431-02c2d8480365
[I 2024-07-09 14:31:55.170 ServerApp] Connecting to kernel efd695ea-963d-410b-b431-02c2d8480365.
[I 2024-07-09 14:31:55.171 ServerApp] Connecting to kernel efd695ea-963d-410b-b431-02c2d8480365.
[I 2024-07-09 14:31:55.172 ServerApp] Connecting to kernel efd695ea-963d-410b-b431-02c2d8480365.
[W 2024-07-09 14:34:59.321 ServerApp] 404 GET /api/contents/.local/lib/python3.10/site-packages/torch/_functorch/deprecated.py?content=0&hash=0&1720550099165 (0a59656efe9c4c488fcb3e9f5f3e74e9@127.0.0.1) 0.61ms referer=https://f200-140-247-111-5.ngrok-free.app/lab
[I 2024-07-09 14:34:59.323 ServerApp] Refusing to serve hidden file or directory '/n/home10/colson/.local/lib/python3.10/site-packages/torch/_functorch/deprecated.py', via 404 Error
[E 2024-07-09 14:34:59.323 ServerApp] Uncaught exception GET /api/contents/.local/lib/python3.10/site-packages/torch/_functorch/deprecated.py?content=0&hash=0&1720550099165 (127.0.0.1)
    HTTPServerRequest(protocol='http', host='f200-140-247-111-5.ngrok-free.app', method='GET', uri='/api/contents/.local/lib/python3.10/site-packages/torch/_functorch/deprecated.py?content=0&hash=0&1720550099165', version='HTTP/1.1', remote_ip='127.0.0.1')
    Traceback (most recent call last):
      File "/n/home10/colson/.conda/envs/gpu/lib/python3.12/site-packages/jupyter_server/services/contents/handlers.py", line 154, in get
        model = await ensure_async(
                ^^^^^^^^^^^^^^^^^^^
      File "/n/home10/colson/.conda/envs/gpu/lib/python3.12/site-packages/jupyter_core/utils/__init__.py", line 198, in ensure_async
        result = await obj
                 ^^^^^^^^^
      File "/n/home10/colson/.conda/envs/gpu/lib/python3.12/site-packages/jupyter_server/services/contents/filemanager.py", line 923, in get
        model = await self._file_model(
                ^^^^^^^^^^^^^^^^^^^^^^^
      File "/n/home10/colson/.conda/envs/gpu/lib/python3.12/site-packages/jupyter_server/services/contents/filemanager.py", line 824, in _file_model
        model = self._base_model(path)
                ^^^^^^^^^^^^^^^^^^^^^^
      File "/n/home10/colson/.conda/envs/gpu/lib/python3.12/site-packages/jupyter_server/services/contents/filemanager.py", line 236, in _base_model
        raise web.HTTPError(404, four_o_four)
    tornado.web.HTTPError: HTTP 404: Not Found (file or directory does not exist: '.local/lib/python3.10/site-packages/torch/_functorch/deprecated.py')
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/n/home10/colson/.conda/envs/gpu/lib/python3.12/site-packages/tornado/web.py", line 1790, in _execute
        result = await result
                 ^^^^^^^^^^^^
      File "/n/home10/colson/.conda/envs/gpu/lib/python3.12/site-packages/jupyter_server/auth/decorator.py", line 73, in inner
        return await out
               ^^^^^^^^^
      File "/n/home10/colson/.conda/envs/gpu/lib/python3.12/site-packages/jupyter_server/services/contents/handlers.py", line 180, in get
        await self._finish_error(
      File "/n/home10/colson/.conda/envs/gpu/lib/python3.12/site-packages/jupyter_server/services/contents/handlers.py", line 114, in _finish_error
        self.write(message)
      File "/n/home10/colson/.conda/envs/gpu/lib/python3.12/site-packages/tornado/web.py", line 914, in write
        raise RuntimeError("Cannot write() after finish()")
    RuntimeError: Cannot write() after finish()
[I 2024-07-09 14:35:41.419 ServerApp] Saving file at /metric-learning/fairness-experiment.ipynb
[I 2024-07-09 14:36:32.450 ServerApp] Saving file at /metric-learning/utils.py
[I 2024-07-09 14:36:49.750 ServerApp] Saving file at /metric-learning/fairness-experiment.ipynb
